module forever_loop;
  int num;
  initial begin 
    forever begin
      num=$urandom_range(0,100);
      $display("THE RANDOM NUMBER=%0d",num);
      if(num inside {[20:40]})
        begin
          $display("%0d IS IN THE RANGE",num);
         $finish;
        end 
       else 
         $display("%0d IS NOT IN THE RANGE THE LOOP RUNS FOREVER",num);
    end 
 end 
endmodule 
OUTPUT:
# KERNEL: THE RANDOM NUMBER=52
# KERNEL: 52 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=74
# KERNEL: 74 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=19
# KERNEL: 19 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=45
# KERNEL: 45 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=92
# KERNEL: 92 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=6
# KERNEL: 6 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=62
# KERNEL: 62 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=69
# KERNEL: 69 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=84
# KERNEL: 84 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=75
# KERNEL: 75 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=85
# KERNEL: 85 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=9
# KERNEL: 9 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=92
# KERNEL: 92 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=36
# KERNEL: 36 IS IN THE RANGE
