module forever_break_loop;
int num;
initial begin 
//GIVING SEED DIFFERENT SEED VALUE 
    void'($urandom(25));
    $display("Seed value= %0d", 25);
    forever begin
      num=$urandom_range(0,100);
      $display("THE RANDOM NUMBER=%0d",num);
      if(num inside {[20:40]})
        begin
          $display("%0d IS IN THE RANGE",num);
         break;
        end 
       else 
         $display("%0d IS NOT IN THE RANGE THE LOOP RUNS FOREVER",num);
end 
end 
endmodule

OUTPUT:
# KERNEL: Seed value= 25
# KERNEL: THE RANDOM NUMBER=42
# KERNEL: 42 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=80
# KERNEL: 80 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=82
# KERNEL: 82 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=90
# KERNEL: 90 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=71
# KERNEL: 71 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=52
# KERNEL: 52 IS NOT IN THE RANGE THE LOOP RUNS FOREVER
# KERNEL: THE RANDOM NUMBER=40
# KERNEL: 40 IS IN THE RANGE
